name: CI nginx test

on:
  push:
    paths:
      - index.html

jobs:
  deploy-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Save SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Copy files to VM
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no index.html Dockerfile ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}:/home/${{ secrets.VM_USER }}/

      - name: Remote deploy and test (DEBUG)
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} <<'EOF'
            set -x  # Включить вывод всех команд

            cd /home/${{ secrets.VM_USER }}

            echo "🛠 Сборка образа"
            docker build -t test-nginx .

            echo "🧹 Удаление старого контейнера (если есть)"
            docker rm -f test-nginx || true

            echo "🚀 Запуск контейнера"
            docker run -d -p 9889:80 --name test-nginx test-nginx || { echo "❌ Ошибка запуска"; docker logs test-nginx || true; exit 1; }

            echo "⏳ Ожидание запуска"
            sleep 10

            echo "📦 Проверка контейнеров:"
            docker ps -a

            echo "📥 curl-запрос к nginx"
            curl -v http://localhost:9889 || { echo "❌ curl неудачен"; exit 1; }

            echo "🔍 Сравнение md5"
            md5sum index.html | cut -d' ' -f1 > original.md5
            curl -s http://localhost:9889 > downloaded.html
            md5sum downloaded.html | cut -d' ' -f1 > downloaded.md5
            diff original.md5 downloaded.md5 || { echo "❌ MD5 не совпадают"; exit 1; }

            # echo "✅ Успешно. Удаляем контейнер"
            # docker rm -f test-nginx
          EOF
